apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-volume
  namespace: kubeflow-user-example-com
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
